### PR TITLE
Fix onPanoramaLoaded

### LINKED ISSUE #54: onPanoramaLoaded is broken
Hi again.

At the moment the component throws a `TypeError: Cannot read property 'on' of null` whenever onPanoramaLoaded is used.

If I had to guess it's because the new code for the different panorama types inits the viewer in the setState callback. Which means by the time the onPanoramaLoaded is called the init function hasn't been called yet, as it runs asynchronously.

### PR DESCRIPTION
**Pull request by m-bp**
Fixes #54 by moving the load event listener to the `init` method

### CODE REVIEW

**Comment by hoaiduyit** [comment]
Hi @m-bp , thank for the support, but next time when you created new PR, please note that all commits are required to be signed.

**Comment by m-bp** [comment]
@hoaiduyit Got it, apologies

**Comment by m-bp** [comment]
@hoaiduyit It seems your 0.2.4 release does not include this commit, however 😅

**Comment by hoaiduyit** [comment]
@m-bp oops, my bad, I forgot to build before publishing. Will patch later.

**Pull request merged**
